export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD';

export const REQUEST_ARTISTS_PENDING = 'REQUEST_ARTISTS_PENDING';
export const REQUEST_ARTISTS_SUCCESS = 'REQUEST_ARTISTS_SUCCESS';
export const REQUEST_ARTISTS_FAILED = 'REQUEST_ARTISTS_FAILED';
